config/routes.rb
Rails.application.routes.draw do

  root 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  get 'admin', :to => 'access#menu'
  #simple match-route for access (doesn't have db table or model)
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

	#resourceful routes 
  resources :subjects do
    member do
      get :delete 
    end
  end


  resources :pages do
    member do
      get :delete 
    end
  end

  resources :sections do
    member do
      get :delete 
    end
  end

  resources :admin_users, :except => [:show] do
    member do
      get :delete 
    end
  end
  
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'
  get 'demo/escape_output'
	get 'test/index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
	
	#find legacy database: self.table_name = "admin_users"

	has_secure_password 
	has_and_belongs_to_many :pages
	has_many :section_edits
	#reach through the section_edits to join sections
	has_many :sections, :through => :section_edits

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\z/i
	FORBIDDEN_USERNAMES = ['turtle', 'butt', 'ghost']

	validates :first_name, :presence => true, :length => { :maximum => 25 }

	validates :last_name, :presence => true, :length => { :maximum => 50 }

	validates :username, :length => { :within => 8..25 }, :uniqueness => true

	validates :email, :presence => true, :length => { :maximum => 100 }, :format => EMAIL_REGEX, :confirmation => true 

	validate :username_is_allowed

	validate :no_new_users_on_monday, :on => :create 

	scope :sorted, lambda { order('last_name ASC', 'first_name ASC')}

	def name
		"#{first_name} #{last_name}"
	end

	private

	def username_is_allowed
		if FORBIDDEN_USERNAMES.include?(username)
			errors.add(:username, "has been restricted!")
		end
	end

	def no_new_users_on_monday
		if Time.now.wday == 1
			errors.add(:base, "No new users on Mondays.")
		end
	end
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

  acts_as_list :scope => :subject 

	belongs_to :subject, { :optional => false }
	
	has_many :sections 
	has_and_belongs_to_many :admin_users
	
	scope :visible, lambda { where(:visible => true) }
	scope :invisible, lambda { where(:visible => false) }
	scope :sorted, lambda { order("position ASC") }
	scope :newest_first, lambda { order("created_at DESC") }

	validates_presence_of :name
	validates_length_of :name, :maximum => 255
	validates_presence_of :permalink, :within => 3..255
	validates_uniqueness_of :permalink 
	


end

app/models/section.rb
class Section < ApplicationRecord

	acts_as_list :scope => :subject 

	belongs_to :page
	has_many :section_edits

	#reach through the section edits rich join table 
	has_many :admin_users, :through => :section_edits

	scope :visible, lambda { where(:visible => true) }
	scope :invisible, lambda { where(:visible => false) }
	scope :sorted, lambda { order("position ASC") }
	scope :newest_first, lambda { order("created_at DESC") }
	
	CONTENT_TYPES = ['text', 'HTML']

	validates_presence_of :name
	validates_length_of :name, :maximum => 255
	validates_inclusion_of :content_type, :in => CONTENT_TYPES, :message => "must be one of: #{CONTENT_TYPES.join(',')}"
	validates_presence_of :content 

end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord
	
	belongs_to :admin_user 
	belongs_to :section
	
end

app/models/subject.rb
class Subject < ApplicationRecord

	acts_as_list

	has_many :pages

	scope :visible, lambda { where(:visible => true) }
	scope :invisible, lambda { where(:visible => false) }
	scope :sorted, lambda { order("position ASC") }
	scope :newest_first, lambda { order("created_at DESC") }
	scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}

	validates_presence_of :name 
	validates_length_of :name, :maximum => 255
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

	layout 'admin'

	before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

  def menu
  	#display text and links
    @username = session[:username]
  end

  def login
  	#display form 
  end

  def attempt_login
  	if params[:username].present? && params[:password].present?
  		found_user = AdminUser.where(:username => params[:username]).first
  		if found_user
  			authorized_user = found_user.authenticate(params[:password])
  		end
  	end

  	if authorized_user
  		session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
  		flash[:notice] = "You are logged in." 
  		redirect_to(admin_path)
  	else
  		flash.now[:notice] = "Invalid"
  		render('login')
  	end

  end

  def logout
  	session[:user_id] = nil
    session[:username] = nil
  	flash[:notice] = 'Logged out'
  	redirect_to(access_login_path)
  end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

	layout 'application' 
	
	#index action is called, and sets the template action to render. 
  def index
  	render('index')
  end

  def hello
  	@array = [1,2,3,4,5]
  	@id = params['id']
  	@page = params[:page]
  	render('hello') 
  end

  def other_hello
  	redirect_to(:action => 'hello')
  end

  def google
  	redirect_to('http://google.com')
  end

  def escape_output
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in
  before_action :find_subject
  before_action :set_page_count, :only => [:new, :create, :edit, :update]

  def index
    @pages = @subject.pages.sorted
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new(:subject_id => @subject.id)   
  end

  def create
    # 'X' which could represent an unecessary db call.
    @page = Page.new(page_params)
    @page.subject = @subject
    if @page.save
      flash[:notice] = "Page '#{@page.name}' created successfully!"
      redirect_to(pages_path(:subject_id => @subject.id))
    else
    
      # before_action :find_subjects hoists our original Subject.sorted to fire at the top of the action at 'X', regardless of save success/fail.  
      # @subjects = Subject.sorted
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(page_params)
      flash[:notice] = "Page '#{@page.name}' updated successfully!"
      redirect_to(page_path(@page, :subject_id => @subject.id))
    else
      # @page_count = Page.count
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Page '#{@page.name}' destroyed successfully!"
    redirect_to(pages_path(:subject_id => @subject.id))
  end

  

  private 

  def page_params
    params.require(:page).permit(:name, :position, :visible, :permalink)
  end


  def find_subject
    @subject = Subject.find(params[:subject_id])   
  end

  def set_page_count 
    #scoped page count by subject 
    @page_count = @subject.pages.count
    if params[:action] == 'new' || params[:action] == 'create'
      @page_count += 1
    end
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

	layout 'public'

  before_action :setup_navigation

  def index
  	#intro text
  end

  def show
  	@page = Page.visible.where(:permalink => params[:permalink]).first
  	if @page.nil?
  		redirect_to(root_path)
  	else
  		#display page content using show.html.erb
  	end
  end

  private 

  def setup_navigation
    @subjects = Subject.visible.sorted 
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def error_messages_for(object)
		render(:partial => 'layouts/error_messages', :locals => {:object => object})
	end




	def status_tag(boolean, options={})
		options[:true_text] ||=''
		options[:false_text] ||''

		if boolean
			content_tag(:span, options[:true_text], :class => 'status true')
		else
			content_tag(:span, options[:false_text], :class => 'status false')
		end
	end

end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
	<div id="error-explanation">
		<h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved </h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<% subjects ||= [] %>
<ul>
<% subjects.each do |subject| %>
  <li>
    <%= subject.name %>
    <ul>
    <% subject.pages.visible.sorted.each do |page| %>
      <li><%= link_to_unless_current(page.name, public_show_path(page.permalink)) %></li>
    <% end %>
    </ul>
  </li>
  <% end %>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sawtell CMS: <%= @page_title || "Admin Area" %></title>
    <%= stylesheet_link_tag('admin', :media => 'all') %>
  </head>

  <body>

    <div id="header">
      <h1> Sawtell CMS Admin</h1>
    </div>
    <div id="main">
      <% if !flash[:notice].blank? %>
    		<div class="notice">
    			<%= flash[:notice] %>
    		</div>
    	<% end %>

  <!-- before yield -->
      <div id="content">
        <%= yield %>
      </div>
    </div>
  <!-- after yield -->
    <div id="footer">
      <p id="copywright">&copy; sawtell</p>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sawtell CMS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag('application', media: 'all') %>
    <%= javascript_include_tag('application') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sawtell CMS<%= " | #{@page_title}" if @page_title %></title>
    <%= stylesheet_link_tag('application', :media => 'all') %>
  </head>
  <body>

    <div id="header">
      <h1>Sawtell CMS</h1>
    </div>
    
    <div id="main">

      <div id="navigation">
        <%= render(:partial => 'layouts/navigation', :locals => { :subjects => @subjects}) %>
      </div>

      <div id="content">
        <%= yield %>
      </div>
      <div class="clear"></div>

    </div>

    <div id="footer">
      <p id="copyright">&copy;sawtell</p>
    </div>

  </body>
</html>

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>
<table summary="Page form fields">
	<tr>
		<th>Name</th>
		<td><%= f.text_field(:name) %></td>
	</tr>
	<tr>
		<th>Subject</th>
		<td><%= f.object.subject.name %></td>
	</tr>
	<tr>
		<th>Permalink</th>
		<td><%= f.text_field(:permalink) %></td>
	</tr>
	<tr>
		<th>Position</th>
		<td><%= f.select(:position, 1..@page_count) %></td>
	</tr>
	<tr>
		<th>Visible</th>
		<td><%= f.check_box(:visible) %></td>
	</tr>
</table>

app/views/pages/delete.html.erb
<!-- <h1>Pages#delete</h1>
<p>Find me in app/views/pages/delete.html.erb</p>
 -->

<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages delete">
	<h2>Delete Page</h2>

	<%= form_for(@page,  :url => page_path(@page, :subject_id => @subject.id), :method => 'delete') do |f| %>

		<p>Are you sure you want to permanently delete this page?</p>

		<p class="referance-name"><%= f.object.name %></p>

		<div class="form-buttons">
			<%= f.submit("Delete Page") %>
		</div>

	<% end %>
</div>

app/views/pages/edit.html.erb
<!-- <h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>
 -->

<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages edit">
	<h2>Edit Page</h2>

	<%= form_for(@page, :url => page_path(@page, :subject_id => @subject.id)) do |f| %>

		<%= render(:partial => 'form', :locals => {:f => f}) %>
	
		<div class="form-buttons">
			<%= f.submit("Edit Page") %>
		</div>
	<% end %>
</div>
	

app/views/pages/index.html.erb
<!-- <h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
 -->
<% @page_title = "All Pages" %>
<%= link_to("<< Back to Subjects", subjects_path, :class => 'back-link') %>

<div class="pages index"> 
	<h2>Pages</h2>

	<%= link_to("Add New Page", new_page_path(:subject_id => @subject.id), :class => 'action new') %>

	<table class="listining" summary="Page list">
		<tr class="header">
			<th>#</th>
			<th>Subject ID</th>
			<th>Page</th>
			<th>Permalink</th>
			<th>Visible</th>
			<th>Sections</th>
			<th>Actions</th>
		</tr>
		<% @pages.each do |page| %>
		<tr>
			<td><%= page.position %></td>
			<td><%= page.subject_id %></td>
			<td><%= page.name %></td>
			<td><%= page.permalink %></td>
			<td class="center"><%= status_tag(page.visible) %></td>
			<td class="center"><%= page.sections.size %></td>
			<td class="actions">
				<%= link_to("View Sections", sections_path(:page_id => page.id), :class => 'action show') %>
				<%= link_to("Show", page_path(page, :subject_id => @subject.id), :class => 'action show') %>
				<%= link_to("Edit", edit_page_path(page, :subject_id => @subject.id), :class => 'action edit') %>
				<%= link_to('Delete', delete_page_path(page, :subject_id => @subject.id), :class => 'action delete') %>
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/pages/new.html.erb
<!-- <h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>
 -->

<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages new">
	<h2>Create Page</h2>

	<%= form_for(@page, :url => pages_path(:subject_id => @subject.id)) do |f| %>

		<%= render(:partial => 'form', :locals => {:f => f}) %>
	
		<div class="form-buttons">
			<%= f.submit("Create Subject") %>
		</div>
	<% end %>
</div>
	

app/views/pages/show.html.erb
<!-- <h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>
 -->

<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages show">
	<h2>Show Page</h2>

	<table summary="Page detail view">
		<tr>
			<th>Name</th>
			<td><%= @page.name %></td>
		</tr>
		<tr>
			<th>Subject ID</th>
			<td><%= @page.subject_id %></td>
		</tr>
		<tr>
			<th>Permalink</th>
			<th><%= @page.permalink %></th>
		</tr>
		<tr>
			<th>Position</th>
			<td><%= @page.position %></td>
		</tr>
		<tr>
			<th>Visible?</th>
			<td><%= @page.visible ? 'true' : 'false' %></td>
		</tr>
		<tr>
			<th>Created</th>
			<td><%= @page.created_at %></td>
		</tr>
		<tr>
			<th>Updated</th>
			<td><%= @page.updated_at %></td>
		</tr>
	</table>
	
</div>